on:
  push:
    branches:
      - main

jobs:
  restart-container:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key directory
        run: |
          mkdir -p /home/runner/.ssh  # SSH 키를 저장할 디렉토리 생성
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa


          echo "--------------1-------------"
          echo "${{ secrets.EC2_PRIVATE_KEY }}"
          echo "--------------2-------------"
          echo /home/runner/.ssh/id_rsa

      - name: Check SSH key permissions and directory contents
        run: |
          ls -al /home/runner/.ssh  # .ssh 디렉토리와 권한 확인
          ls -al /home/runner/.ssh/id_rsa  # id_rsa 파일의 권한 확인
          ls -ld /home/runner/.ssh  # .ssh 디렉토리 권한 확인

      - name: Set up SSH key with ssh-agent
        run: |
          eval $(ssh-agent -s)
          ssh-add /home/runner/.ssh/id_rsa

      - name: SSH into EC2 and Restart Docker Container
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop worldengin_container || true
            docker rm worldengin_container || true
            docker run -d --name worldengin_container worldengin_image

