on:
  push:
    branches:
      - main

jobs:
  restart-container:
    runs-on: ubuntu-latest

    steps:
      - name: Decode and set permissions for SSH key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set up SSH key with ssh-agent
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: SSH into EC2 and Restart Docker Container
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop worldengin_container || true
            docker rm worldengin_container || true
            docker run -d --name worldengin_container worldengin_image

